# SQL Order By Exercises

In [1]:
import pandas as pd
import sqlite3
import pandasql

conn = sqlite3.connect('flights.db')
cur = conn.cursor()

## Exercise 1:
Select al records from the airports table, sort the results alphabetically by column city.

In [2]:
pd.read_sql('''
SELECT *
FROM airports
ORDER BY city
''', conn)

,index,id,name,city,country,code,icao,latitude,longitude,altitude,offset,dst,timezone
0,6975,8404,South Cariboo Regional Airport,108 Mile Ranch,Canada,ZML,CZML,51.4412,-121.1958,3129,-8,A,America/Vancouver
1,5343,6472,Aaa,Aaa,Maldives,None,\N,73.9,3.222,0,5,U,\N
2,4055,4165,Flugplatz Merzbrueck,Aachen,Germany,AAH,EDKA,50.823194,6.186389,570,1,E,Europe/Berlin
3,7335,8767,Aachen HBF,Aachen,Germany,None,\N,50.7667,6.1,873,1,E,Europe/Berlin
4,620,628,Aalborg,Aalborg,Denmark,AAL,EKYT,57.092789,9.849164,10,1,E,Europe/Copenhagen
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8102,5448,6784,Tekirdağ Çorlu Airport,Çorlu,Turkey,TEQ,LTBU,41.13825,27.919094,574,2,E,Europe/Istanbul
8103,4539,5782,Île d'Yeu Airport,Île d'Yeu,France,IDY,LFEY,46.718611,-2.391111,79,1,E,Europe/Paris
8104,4401,5921,Île des Pins Airport,Île des Pins,New Caledonia,ILP,NWWE,-22.5889,167.456,315,11,U,Pacific/Noumea
8105,4728,5593,Östersund Airport,Östersund,Sweden,OSD,ESNZ,63.1944,14.5003,1233,1,E,Europe/Stockholm
8106,4515,5806,Žilina Airport,Žilina,Slovakia,ILZ,LZZI,49.231528,18.6135,1020,1,E,Europe/Bratislava

## Exercise 2:
Select all records from the airports table, sortthe result reversed alphabetically by the column city.

In [4]:
pd.read_sql('''
SELECT *
FROM airports
ORDER BY city DESC
''', conn)

,index,id,name,city,country,code,icao,latitude,longitude,altitude,offset,dst,timezone
0,4515,5806,Žilina Airport,Žilina,Slovakia,ILZ,LZZI,49.231528,18.6135,1020,1,E,Europe/Bratislava
1,4728,5593,Östersund Airport,Östersund,Sweden,OSD,ESNZ,63.1944,14.5003,1233,1,E,Europe/Stockholm
2,4401,5921,Île des Pins Airport,Île des Pins,New Caledonia,ILP,NWWE,-22.5889,167.456,315,11,U,Pacific/Noumea
3,4539,5782,Île d'Yeu Airport,Île d'Yeu,France,IDY,LFEY,46.718611,-2.391111,79,1,E,Europe/Paris
4,5448,6784,Tekirdağ Çorlu Airport,Çorlu,Turkey,TEQ,LTBU,41.13825,27.919094,574,2,E,Europe/Istanbul
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8102,620,628,Aalborg,Aalborg,Denmark,AAL,EKYT,57.092789,9.849164,10,1,E,Europe/Copenhagen
8103,4055,4165,Flugplatz Merzbrueck,Aachen,Germany,AAH,EDKA,50.823194,6.186389,570,1,E,Europe/Berlin
8104,7335,8767,Aachen HBF,Aachen,Germany,None,\N,50.7667,6.1,873,1,E,Europe/Berlin
8105,5343,6472,Aaa,Aaa,Maldives,None,\N,73.9,3.222,0,5,U,\N
8106,6975,8404,South Cariboo Regional Airport,108 Mile Ranch,Canada,ZML,CZML,51.4412,-121.1958,3129,-8,A,America/Vancouver

## Exercise 3:
Select all records from te airports table, sort the result alphabetically, first by the column country, then by the column city.

In [5]:
pd.read_sql('''
SELECT *
FROM airports
ORDER BY country, city
''', conn)

,index,id,name,city,country,code,icao,latitude,longitude,altitude,offset,dst,timezone
0,7393,8825,Bamyan Airport,Bamyan,Afghanistan,BIN,OABN,34.816667,67.816667,2550,4.5,N,Asia/Kabul
1,6442,7868,Camp Bastion,Camp Bastion,Afghanistan,None,OAZI,31.865556,64.195278,2808,4.5,N,Asia/Kabul
2,6076,7501,Chaghcharan Airport,Chaghcharan,Afghanistan,CCN,OACC,34.526667,65.271667,7383,4.5,U,Asia/Kabul
3,4400,5922,Faizabad Airport,Faizabad,Afghanistan,FBD,OAFZ,37.1211,70.5181,3872,4.5,U,Asia/Kabul
4,2007,2048,Herat,Herat,Afghanistan,HEA,OAHR,34.210017,62.2283,3206,4.5,U,Asia/Kabul
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8102,989,1007,Mutoko,Mutoko,Zimbabwe,None,FVMT,-17.431917,32.184502,3950,2,U,Africa/Harare
8103,2147,6866,Spray View Airport,Spray View,Zimbabwe,None,FVSV,-17.917,25.817,3210,2,U,Africa/Harare
8104,986,1004,Victoria Falls Intl,Victoria Falls,Zimbabwe,VFA,FVFA,-18.095881,25.839006,3490,2,U,Africa/Harare
8105,6273,7699,Shearwater Heliport,Victoria Falls,Zimbabwe,None,\N,-17.911443,25.828167,3937,2,U,Africa/Harare
8106,992,1010,Zvishavane,Zvishavane,Zimbabwe,None,FVSH,-20.289497,30.088228,3012,2,U,Africa/Harare